---
- name: "configuration play."
  hosts: web
  user: ubuntu
  gather_facts: false
  ansible_connection = ssh
  vars:
    - ansible_python_interpreter: /usr/bin/python3
    - ansible_host_key_checking: false
    - ansible_stdout_callback: yaml
    - ansible_host_key_checking: false

  roles:
    - configure-server
